name: Keep Render App Warm

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes UTC
  workflow_dispatch:        # Allows manual runs

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl homepage
        run: curl -s -o /dev/null https://ruthselormeacolatse.onrender.com/
